### ISSUE TITLE
[BUG] drop duplicates not working for columns not specified

### ISSUE THREAD

**Issue by nkarpov** [MrPowers/mack#25]
I added a PR for this test case that's failing: https://github.com/MrPowers/mack/pull/24

The issue is that [in these lines ](https://github.com/MrPowers/mack/blob/main/mack/__init__.py#L188-L209), the `else` branch (when no columns are provided), the function reduces to kill_duplicates.

**Comment by robertkossendey** [comment]
I will take care of this, thank you for reporting that bug! :)

**Comment by robertkossendey** [comment]
The problem is that we expect to have at least one unique column, otherwise drop_duplicates will always default to kill_duplicates. It is essentially the same issue I referred to [here](https://github.com/MrPowers/mack/pull/9#issue-1500513007).

We should agree on what the API of drop_duplicates should be (e.g. required unique primary column + set of duplication columns) and if it is okay to overwrite instead of merge in case that there is no alternative.
@MrPowers

**Comment by MrPowers** [comment]
@robertkossendey - I think it's better to require one unique column rather than falling back to `kill_duplicates`.

Few questions:

* what should we do if the user supplies a primary key column that's not unique?
* we should probably have some additional helper functions.  One function to determine if a column is unique, another function to add a UUID column, another function to add a surrogate key (perhaps a MD5 hash of user supplied columns).  

Deduplicating a Delta table while factoring in all the edge cases and providing an intuitive end user API is surprisingly challenging.

**Comment by nkarpov** [comment]
I think the issue is that the underlying store does not provide any unique constraints (yet) and forcing us to consider questions like that.

We should assume the collection is a multiset (because it is) aka. drop the idea of a primary key altogether, and have the same API as [dropDuplicates](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.dropDuplicates.html?highlight=dropduplicates#pyspark.sql.DataFrame.dropDuplicates)

**Comment by robertkossendey** [comment]
@MrPowers I agree, falling back to kill_duplicates was not intentional and is a bug.

@nkarpov but how are we supposed to provide the same API as dropDuplicates if the table looks like that:

data = [
        (1, "A", "A", "C"),
        (1, "A", "A", "C"), 
        (1, "A", "A", "C"),
        (1, "A", "A", "C"),
    ]

The only way that I see would be to completely overwrite the existing table, am I missing something?

**Comment by nkarpov** [comment]
I think the answer is this functionality should exist in core Delta implementations (spark connector, rust, etc.) that expose file level APIs. A potential implementation could look similar to `MERGE`: find the files where duplicates exist and rewrite only those files (minus the duplicates). Otherwise, yes, I think overwriting the table is the only option using public APIs. Maybe there's still a more clever solution...

**Comment by robertkossendey** [comment]
I agree, this functionality should eventually exist in core Delta. Until then I see two different approaches that we could take with our implementation:

1. dropDuplicates-like API where we overwrite the table. Not performant, but a dropDuplicates operation on a table is not something you would do hourly, so maybe it is acceptable
2. Use the existing primary key approach, but make the duplicate columns required and check whether the PK column is actually unique.

**Comment by MrPowers** [comment]
@robertkossendey - I vote for two separate public interface methods with the different implementations in that case.

1. `drop_duplicates` which does something like `deltaTable.toDF().dropDuplicates(col1, col2).write.format("delta").mode("overwrite")...`
2. `drop_duplicates_pkey` which uses the existing primary key approach.  I don't think we should check whether the PK column is actually unique cause that would slow down the function (or make this check default to off, but let users run it by setting a flag if they want).  

We can document the two methods, explain the tradeoffs and let users decide what's best for their situation.

Working through this problem in detail is making me realize the value that mack will offer end users.  Most Delta Lake users aren't going to want to fully think through this problem when all they want is to deduplicate their Delta table.

**Comment by robertkossendey** [comment]
@MrPowers great! Then I will create a PR later with both methods, tests & documentation.

I agree, the raw Delta Lake APIs are lacking some convenience features and mack can be very helpful there 🎉

**Comment by MrPowers** [comment]
This is fixed, thanks @robertkossendey
